In [ ]:
# 배열의 index 접근

import numpy as np

In [ ]:
# 1차원 배열

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = np.arange(10)
print(arr)

print(arr[3])
print(arr[1])

In [ ]:
print(arr[10]) # size외의 값을 불러오면 에러나 감

In [ ]:
# 2차원 배열

arr = np.arange(1, 13)
arr = arr.reshape(3, 2, 2)

print(arr, arr.shape, arr.ndim)

In [ ]:
arr = np.arange(10)

print(arr[3:8])

In [ ]:
print(arr[3:])

In [ ]:
print(arr[:7])

In [ ]:

arr = np.arange(1, 13)
arr = arr.reshape(3, 4)

print(arr,"\n\n\n")
print(arr[0, :])

In [ ]:
print(arr[:, 1])

In [ ]:
print(arr[:3, :])

In [ ]:
print(arr[:2, 2:])

In [4]:
# fancy indexting
#특정 인덱스를 여려개 입력해서 탐색하는 방법

# 1차원배열

arr = np.linspace(5, 30, 6)
print(arr)
print(arr[[0, 2, 4]])

[ 5. 10. 15. 20. 25. 30.]
[ 5. 15. 25.]


In [5]:
arr = np.arange(5, 61, 5)
arr = arr.reshape(3, 4)

print(arr)
print(arr[[0,2], 2:])

[[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]]
[[15 20]
 [55 60]]


In [6]:
print(arr[1:, [2, 3]])

[[35 40]
 [55 60]]


In [7]:
# 배열의 boolean 인덱싱 -> true, false를 이용해서 값을 탐색

# 1차원

arr = np.array([1, 2, 3, 4])
print(arr[[True, False, True, True]])

[1 3 4]


In [8]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])

print(arr[[True, False], True])

[[1 2 3 4]]


In [9]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])

print(arr[arr > 4])

[5 6 7 8]


In [10]:
print(arr[arr > 2])

[3 4 5 6 7 8]


In [12]:
print(arr[arr <= 5])

[1 2 3 4 5]
